### ISSUE TITLE
Epic Games Doesnt work

### ISSUE THREAD

**Issue by DiabolicAngeL** [Axyss/AutomatiK#2] opened 2020-12-31 13:26 UTC
Hello, the epic games module doesn't work. It doesn't post anything.

Also, is there anyway to start the bot in the channel without having to type !mk start everytime the bot restarts?

Thanks!

**Comment by Axyss** [comment] 2020-12-31 15:59
Hello, the bug you mentioned is going to be solved in the upcoming update, which will be released in a matter of days.
However, It is possible to fix It right now by replacing the **epic.py** module for the one inside the attached zip, It is a temporary fix I made that I didn't push to the repository because I thought I could have finished the update sooner.

File: [epic_mod.zip](https://github.com/Axyss/AutomatiK/files/5757656/epic_mod.zip)
(It has only been tested on version 1.2_3)

Hope this helps!

**Comment by DiabolicAngeL** [comment] 2020-12-31 16:07
> Hello, the bug you mentioned is going to be solved in the upcoming update, which will be released in a matter of days.
> However, It is possible to fix It right now by replacing the **epic.py** module for the one inside the attached zip, It is a temporary fix I made that I didn't push to the repository because I thought I could have finished the update sooner.
> 
> File: [epic_mod.zip](https://github.com/Axyss/AutomatiK/files/5757656/epic_mod.zip)
> (It has only been tested on version 1.2_3)
> 
> Hope this helps!

Thank you very much!
What about starting the bot in the channel automatically without having to type the command each time? Will that be possible?

**Comment by Axyss** [comment] 2020-12-31 16:53
Oops, my fault, I forgot to answer your question. Regarding the "!mk start" topic, I plan to work on It in the future. Nevertheless, the next update will introduce a new command that will let server administrators reload the bot's configuration, language packages, and modules without restarting, which are very common reasons to do so. 

> It doesn't show the game's picture. Maybe it's not possible with epic games, I'm just saying.

This will be fixed in the future by scraping the photos manually and creating a Discord embedded message with It that will contain more information about the game as well.

> It doesn't save the settings, every time it is restarting it starts clean

I recommend you try the beta version, It can be found on the **beta** branch. If the problem persists open a new Issue explaining how to reproduce the bug, your OS, and any error messages if there are.

About the language on Epic Games, this should fix it: 
[epic_mod.zip](https://github.com/Axyss/AutomatiK/files/5757740/epic_mod.zip)

**Comment by DiabolicAngeL** [comment] 2020-12-31 17:02
I saw about the language after I posted. x)
Thank you very much once again for the help!

**Closed** 2020-12-31 17:12 UTC
Labels: bug, suggestion
